- README.md
> Adding .org site link

- index.html
> Fixing team meeting section text

- index.html
> Adding link to cncf  public events calendar

- index.html
> Adding KubeCon 2020 Serverless Wg Pres

- index.html
> Adding serverless practiotioners summit pres

- index.html
> Adding DevNation talk

- index.html
> Updating nav links

- index.html
> Update zoom meeting link

- index.html
> Fix for sdk dropdown colors on safari

- css/sws.css
- index.html
> adding kubecone info

- index.html
> fix for kubecon info

- index.html
Adds project office hours links to website
> Adding Kubecon project office hours links

- index.html
> Update community meeting info

- index.html
> Adding intro video to resources section

- index.html
> Addinlinevideos

- css/sws.css
- index.html
> update for release

- js/swedtior.js
> update diagram service endpoint to use https

- editor.html
> adding home link on editor page

- editor.html
> Editor dropdown fix for FireFox

- editor.html
- js/swedtior.js
> Editor color themes

- editor.html
> Update editor page nav links

- css/sws.css
> Fix active tab color

- css/sws.css
- index.html
> fix for tabs borders

- index.html
> update meeting info text in contribute section

- index.html
> adding new hands-on series video

- index.html
> adding videos to resources

- index.html
> adding next meet message

- index.html
> update next meet date

- index.html
> small change to title text

- _redirects
- js/swedtior.js
> Adding diagram service generation endpoint to the website

- index.html
> update next meet day and latest java sdk version

- index.html
- js/accordion.js
> small updates for mobile

- index.html
> fix for accordion width

- css/sws.css
- index.html
> update accordion tabs

- index.html
> fix padding

- index.html
> made main text smaller

- editor.html
- index.html
Examples link is broken and this PR fix it
> Fix examples broken link

- index.html
> update for next community meeting

- index.html
> update next team meet date

- index.html
> dynamically figure out next meet date

- schemas/0.6/workflow.json
- schemas/0.7-alpha/workflow.json
> fix for foreach state schema

- _redirects
> update service diagrams url

- js/swedtior.js
> update editor examples

- js/swedtior.js
- js/workflowschema.js
> online editor schema fixes

- index.html
> update release versions and add release notification

- js/workflowschema.js
> update editor schema

- index.html
> adding project office hours info

- index.html
> Adding SDKs

- index.html
> adding slack link in nav

- index.html
> add open source and sponsor info

- index.html
> adding synapse to website

- index.html
> fixing font sizes

- index.html
> fixing missing links

- index.html
> fixed spelling error

- _redirects
- schemas/0.6/common.json
- schemas/0.6/events.json
- schemas/0.6/extensions/kpi.json
- schemas/0.6/functions.json
- schemas/0.6/retries.json
- schemas/0.6/workflow.json
- schemas/0.7/common.json
- schemas/0.7/events.json
- schemas/0.7/extensions/kpi.json
- schemas/0.7/functions.json
- schemas/0.7/retries.json
- schemas/0.7/workflow.json
> update all schema ids and redirects

- index.html
> adding kubecon eu 21 talk

- schemas/0.6/workflow.json
> update 06 schemas

- schemas/0.7/secrets.json
- schemas/0.7/workflow.json
> update 07 schema and add secrets

- schemas/0.6/workflow.json
> update 06 schema to latest

- index.html
> Adding Ricardos OpenShift Commons talk

- index.html
> Add announce for TypeScript SDK

- index.html
> fix latest go release in table

- index.html
> Update .NET SDK latest version

- schemas/0.7/auth.json
- schemas/0.8/auth.json
> fix auth schema typo

- index.html
> announce 0.7

- schemas/0.7/errors.json
- schemas/0.8/errors.json
> add missing errors json schemas

- index.html
> adding twitter and some updates

- index.html
> adding back online editor link in nav

- index.html
> adding back sponsor link

- editor.html
- js/serverlessWorkflowSdk.umd.js
- js/swedtior.js
> added diagram generation with mermaidjs

- index.html
> add office hours embedded video

- index.html
> add border to cards

- index.html
> fix runtimes link

- index.html
> small update to code samples

- index.html
> small fix for section title

- index.html
> fix typo in text

- editor.html
Signed-off-by: manick02 <manickavasagam.sundaram@gmail.com>
> #140 Update workflow schema reference from site

- community.html
> fix community page links and text

- community.html
> small update

- index.html
> add date for third workshop

- index.html
> fix events section

- community.html
- index.html
> updated next workshop date and added yuris twitter id

- schemas/0.9/workflow.json
> update 09 schema

- index.html
> adding second workshop youtube link

- index.html
> update workshop 3 date time

- index.html
- index_old.html
> add-sdk-python

- index.html
> Removing Red Hat from list of comps

- index.html
> revert last commit

- index.html
> Added 3rd Workshop recording and link to next one

- index.html
> update next workshop date

- index.html
> Added link to latest JSON Schema

- _headers
> Added permissive CORS headers

- index.html
> fix text in sponsor section

- index.html
> add project meetings

- index.html
> update project meeting as series

- index.html
> update next meetup date

- .github/CODEOWNERS
- .github/OWNERS
- community.html
- index.html
> updated community info

- index.html
> up workshop date

- index.html
> update workshop date

- index.html
this just adds the youtube url for last workshop and adds new row for next workshop tentative date
> Adding next workshop date and update last workshop youtube url

- index.html
just adding link to latest workshop recording (also adds description field so readers can tell what the workshop is about)
> Add new workshop recording

- index.html
> up workshop info

- index.html
> Update EventMesh links

- index.html
Fixes: https://github.com/serverlessworkflow/serverlessworkflow.github.io/issues/185
> Updated Red Hat info

- index.html
> remove luma links

- index.html
Add back our weekly meetings 🤗 
I've added a new link to the events section. Feel free to suggest a new design, but make sure to take a look at the Netlify preview.
The links are redirecting to CNCF's calendar page.
> Add back our weekly meetings

- content/en/_index.md
> Removed Temporal from "Trusted by top brands in workflow technologies"

- content/en/blog/releases/release-1.0.0-alpha3.md
A blog for 1.0.0-rc3 announcement + notable issues.
I'll use this blog post to advertise on LinkedIn and X.
> Release 1.0.0-rc3 announcement blog

- content/en/blog/releases/release-1.0.0-alpha3.md
Small fix to add the correct date to the post.
> Update date on release 1.0.0-rc3 post

- content/en/blog/releases/release-synapse-1.0.0-alpha5.2.md
Adds a new blog post announcing Synapse 1.0.0-alpha5.2 and its new light theme.
> Synapse light theme annoucement

- content/en/blog/releases/release-sdk-java-7.0.0-alpha5.md
> Release 7.0.0-alpha5

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- Adds form-based issue templates
> Add form-based issue templates

- .netlify/v1/config.json
- package-lock.json
- src/content.config.ts
- src/content/examples/async-api.md
- src/content/examples/container.md
- src/content/examples/emit.md
- src/content/examples/for.md
- src/content/examples/fork.md
- src/content/examples/grpc.md
- src/content/examples/http.md
- src/content/examples/listen.md
- src/content/examples/open-api.md
- src/content/examples/raise.md
- src/content/examples/script.md
- src/content/examples/subflow.md
- src/content/examples/switch.md
- src/content/examples/try.md
- src/content/examples/wait.md
- src/pages/index.astro
- Adds more samples
- Organizes samples as content
> Add Samples

- src/content/blog/releases/release-sdk-typescript-1.0.0-alpha5.md
This adds a new blog entry to announce the release of the TS SDK v1.0.0-alpha5.0
> TS SDK v1.0.0-alpha5.0 announcement

- src/pages/index.astro
Added PHP and Rust SDK
Closes #227
> Added PHP and Rust SDK

- src/pages/index.astro
- updated key benefits
- added link to use cases
Closes #240
> Updates key benefits

- src/content/blog/releases/release-sdk-go-3.0.0.md
> Remove unnecessary title from the go sdk announcement

- _redirects
- public/schemas/1.0.0/workflow.json
- public/schemas/1.0.0/workflow.yaml
- src/consts.ts
- src/content/blog/releases/release-1.0.0.md
- src/content/examples/async-api.md
- src/content/examples/container.md
- src/content/examples/emit.md
- src/content/examples/for.md
- src/content/examples/fork.md
- src/content/examples/grpc.md
- src/content/examples/http.md
- src/content/examples/listen.md
- src/content/examples/open-api.md
- src/content/examples/raise.md
- src/content/examples/script.md
- src/content/examples/subflow.md
- src/content/examples/switch.md
- src/content/examples/try.md
- src/content/examples/wait.md
- src/pages/index.astro
- Added v1 schemas
- Updated examples for v1
- Added v1 announcement blog post
> v1.0.0 announcement

- src/content/blog/events/serverless-workflow-at-fosdem-2025-recording.md
This PR adds a blog post to promote the recording of the FOSDEM 2025 "Introduction to Serverless Workflow DSL" presentation.
> Add FOSDEM 2025 recording announcement blog post

- src/content/blog/releases/release-sdk-java-7.1.0.md
> SDK 7.1.0 release

- package-lock.json
- src/content/blog/releases/release-sdk-java-7.2.0.md
A simple blog to announce the new Java SDK release.
Please merge if you see fit.
> Java SDK 7.2.0.Final Release Announcement
